name: QloyalCodeTestgit remote add origin git@github.com:sominwani/q-loyal-code-test.git Test Suite CI

on:
  push:
    branches:
      - "!main"
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Install dependencies
        run: mvn clean install --no-transfer-progress

      - name: Run tests
        run: mvn test

      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cucumber-html-report
          path: target/cucumber-report.html
